---
title: "Comparing Frontloaded Genes to WGCNA Module Membership - are there"
author: "Zoe Dellaert"
date: "7/19/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a Rmd file analyzing our raw count data by the glmmSeq package as described in the [vignette](https://cran.r-project.org/web/packages/glmmSeq/vignettes/glmmSeq.html) and [manual](https://cran.r-project.org/web/packages/glmmSeq/glmmSeq.pdf).

```{r}
sessionInfo() #provides list of loaded packages and version of R. I still have version 4.1 for now.
```

```{r cars}
library(dplyr)
library(reshape2)
library
sessionInfo() #list of packages after library-ing these packages
```

2631 genes are frontloaded, with a yall ratio larger than 1 and a xall_1 ratio less than 1.

```{r}
frontloaded_genes <- read.csv("../../../output/glmmseq/frontloaded_genes.csv") %>% select(-"X")

WGCNA_ModuleMembership <- read.csv("../../../output/WGCNA/WGCNA_ModuleMembership.csv") %>% rename("Gene" = X)

WGCNA_ModuleEigengenes <- read.csv("../../../output/WGCNA/WGCNA_ModuleEigengenes.csv") %>% rename("Coral_ID" = X)
```

```{r}
frontloaded_modules_full <- left_join(frontloaded_genes, WGCNA_ModuleMembership)

frontloaded_modules <- left_join(frontloaded_genes, WGCNA_ModuleMembership) %>% group_by(moduleColor) %>% summarize(col_n = n()) %>% arrange(desc(col_n))
```

```{r}
modules <- WGCNA_ModuleMembership %>% group_by(moduleColor) %>% summarize(total_col_n = n()) %>% arrange(desc(total_col_n))
```

```{r}
proportions <- left_join(modules, frontloaded_modules) %>% mutate(prop = col_n/total_col_n)

proportions

proportions %>% arrange(desc(prop))
```


Lets also pull in our metadata

```{r}
coldata <- read.csv("../../../../RAnalysis/Data/RNA Submission Sample List metadata.csv") #read in metadata file
coldata <- plyr::rename(coldata, c("Sample.Name"="Coral_ID")) #Make a column that represents the colonies
coldata$Colony <- gsub("A", "", coldata$Coral_ID) #ID which sample is from which colony by remobing letters after colony name
coldata$Colony <- gsub("B", "", coldata$Colony) #ID which sample is from which colony by remobing letters after colony name
coldata$Colony <- gsub("C", "", coldata$Colony) #ID which sample is from which colony by remobing letters after colony name
coldata$Colony <- gsub("D", "", coldata$Colony) #ID which sample is from which colony by remobing letters after colony name

coldata$Origin <- factor(coldata$Origin) #set variables to factors
coldata$Colony <- factor(coldata$Colony) #set variables to factors
coldata$Treatment <- factor(coldata$Treatment) #set variables to factors

coldata <- coldata %>% filter(Coral_ID != c("RF16A","RF16C")) #removed outlier rows from metadata
head(coldata)
```


```{r}
by_gene <- frontloaded_modules_full %>% select(c(30:75,87))

avgs_module <- by_gene %>% tidyr::pivot_longer(cols = 1:46, names_to = "Coral_ID", values_to = "Gene_value") %>% group_by(moduleColor,Coral_ID) %>% summarise(Module_avg = mean(Gene_value))

avgs_module <- merge(coldata, avgs_module, by = 'Coral_ID')
```


```{r}
library(reshape2)
library(ggplot2)

png("../../../output/glmmseq/frontloaded_by_module.png", 1000, 1000, pointsize=10)
ggplot(avgs_module, aes(x=Treatment, y=Module_avg, fill = factor(Origin), shape=Origin)) +
  geom_boxplot(aes(middle = mean(Module_avg)), position=position_dodge(0.8), outlier.size = 0, alpha = 0.5) + 
  stat_summary(fun.y = mean, color = "black", position = position_dodge(0.75),
               geom = "point", shape = 19, size = 3,
               show.legend = FALSE) +
  ylab("ModuleEigengene") +
  #ylim(-0.1,0.1) +
  scale_color_manual(values=c("#56B4E9","#D55E00")) +
  geom_hline(yintercept=0, linetype='dotted', col = 'black', size = 1)+
  theme_classic() +
  #theme(legend.position = "none") +
  facet_wrap(~moduleColor)
dev.off()
```

```{r}
library(reshape2)
library(ggplot2)

MEs_table <- WGCNA_ModuleEigengenes  # new table for plotting 
MEsPlotting <- merge(coldata, MEs_table, by = 'Coral_ID') # merge
MEsPlotting <- MEsPlotting %>% select(-"Colony") # ommit the Colony data to just plot the module colors 

#reorder columns to match the order on the WGCNA module plot
desired_order <- c("Coral_ID" , "Origin", "Treatment","MEblack", "MEred" , "MEsalmon" , "MEturquoise","MEmidnightblue", "MEgrey60","MEmagenta", "MEgreen" ,  "MEpurple" ,"MEtan", "MElightcyan" , "MEbrown" , "MEcyan" , "MEgreenyellow",   "MEpink" ,"MEblue" ) 

MEsPlotting <- MEsPlotting %>% select(all_of(desired_order))

MEsPlotting_melt <- melt(MEsPlotting, id=c('Coral_ID', 'Origin', 'Treatment'))
#plot it

png("../../../output/glmmseq/frontloaded_by_module_eigengene.png", 1000, 1000, pointsize=10)
ggplot(MEsPlotting_melt, aes(x=Treatment, y=value, fill = factor(Origin))) +
  geom_boxplot(aes(middle = mean(value)), position=position_dodge(0.8), outlier.size = 0, alpha = 0.5) + 
  geom_point(aes(color = Origin), position=position_dodge(0.8), alpha = 0.5) + 
  ylab("ModuleEigengene") +
  ylim(-0.5,0.5) +
  #scale_color_manual(values=c("#D55E00","#56B4E9")) + scale_fill_manual(values=c("#D55E00","#56B4E9")) +
  geom_hline(yintercept=0, linetype='dashed', col = 'black', size = 0.5)+
  theme_classic() +
  theme(legend.position = "none",
        panel.border = element_rect(color = "black", fill = NA, size = 1)) +  # Add panel border
  facet_wrap(~variable)
dev.off()
```

